# GCD and LCM 2

Previously, we looked at how to compute the GCD and LCM of two natural numbers both by hand and programmatically. However, what if we are interested in determining the GCD and LCM of four, five or any number of natural numbers? How do we do this? The answer is simple: break down the problem into manageable pieces which you then work through. So, for four numbers, we would find the GCD of the first two numbers, take that answer and find the GCD of the answer and the third number and finally find the GCD of the resulting answer and the last number. The same applies to the LCM. Finding the GCD and the LCM of more than two natural numbers is thus an iterative process that involves repeated use of the GCD and LCM functions for two natural numbers.

As an example, let us find the GCD of the numbers 500, 8, 50 and 70. 
$$
\begin{aligned}
\text{gcd}(500, 8) &= \text{gcd}(8, 4)  \\
 &= \text{gcd}(4, 0) \\
 &= 4 \\
 \\
\text{gcd}(4, 50) &= \text{gcd}(50, 4) \\
 &= \text{gcd}(4, 2) \\
 &= \text{gcd}(2, 0) \\
 &= 2 \\
 \\
\text{gcd}(2, 70) &= \text{gcd}(70, 2) \\
 &= \text{gcd}(2, 0) \\
 &= 2 \\
\text{So, the GCD of 500, 8, 50 and 70} &= 2
\end{aligned}
$$

Also, let's find the LCM of the four numbers 500, 8, 50 and 70. 
$$
\begin{aligned}
\text{lcm}(500, 8) &= \frac{|500 \times 8|}{\text{gcd}(500, 8)} \\
 &= \frac{\text{4,000}}{4} \\
 &= \text{1,000} \\
 \\
\text{lcm}(\text{1,000}, 50) &= \frac{|\text{1,000} \times 50|}{\text{gcd}(\text{1,000}, 50)} \\
 &= \frac{\text{1,000} \times 50}{50} \\
 &= \text{1,000} \\
 \\
\text{lcm}(\text{1,000}, 70) &= \frac{|\text{1,000} \times 70|}{\text{gcd}(\text{1,000}, 70)} \\
\text{But: gcd}(\text{1,000}, 70) &= \text{gcd}(70, 20) \\
 &= \text{gcd}(20, 10) \\
 &= \text{gcd}(10, 0) \\
 &= 10 \\
\text{Thus, lcm}(\text{1,000}, 70) &= \frac{\text{1,000} \times 70}{10} \\
 &= 100 \times 70 \\
 &= \text{7,000} \\
\text{Hence, the LCM of 500, 8, 50 and 70} &= \text{7,000}
\end{aligned}
$$

The following Python code demonstrates how to programmatically determine the GCD and LCM of more than two numbers. The Python code relies on the function definitions for the gcd() and lcm() funtions from the previous GCD and LCM post [Insert link to GCD and LCM post].

``` python
# Assuming the gcd and lcm functions have already being
# defined or imported

# Extended version of the GCD function
def gcd_ext(arr):
    # arr is a list of natural numbers
    ans = gcd(arr[0], arr[1])
    i = 2
    while i < len(arr):
        ans = gcd(ans, arr[i])
        i += 1
    return ans
    
# Extended version of the LCM function
def lcm_ext(arr):
    ans = lcm(arr[0], arr[1])
    i = 2
    while i < len(arr):
        ans = lcm(ans, arr[i])
        i += 1
    return ans
    
# Test the extended versions of the GCD and LCM functions
print("GCD([500, 8, 50, 70]):", gcd_ext([500, 8, 50, 70]))  # Ans: 2
print("LCM([500, 8, 50, 70]):", lcm_ext([500, 8, 50, 70]))  # Ans: 7000
```
